### PR TITLE
Add support for NRF52x devices

### PR DESCRIPTION
**Pull request by TMRh20**
I was bored this weekend, so put together a preliminary PR for NRF52x support based on the nrf_to_nrf driver
- Support NRF52x
- Increase max nodes from 6 to 7 (uses all 6 pipes on each radio)
- Change myAddress from int to uint8_t
- Add constructor for NRF52x with no CE/CS pins
- Declare a receive packet for reception of data
- 0 out the buffer, counter and address when a new packet is created
- Remove unnecessary start and stop listening calls
- Modify examples to use a timer based delay for sending instead of an actual delay() call since NRF52x is software driven and available() needs to be called constantly
- Update related documentation
- #3

### CODE REVIEW

**Comment by Hobietime** [comment]
Hi! 

Thanks for putting in this work over the weekend.

Could you explain the change from 6 to 7 nodes?

Its been quite a while since I worked with this radio, so I might be misremembering things.

I remember that there are 6 pipes available on each radio, and if I recall correctly, each is used each like an address.

If that is the case, How can there be 7 nodes? How would the 7th node have an address?

Also, I see you fixed an off by one error in the pipe indexing, according to the latest documentation.

Was there ever a time when your library's pipes were 1 indexed? Or did I just always have that bug in there?

**Comment by Hobietime** [comment]
I read through everything a bit more and remembered the addressing scheme has both addresses and pipes, so we should get a complete graph of 7 nodes with 6 pipes. 

pir-2-1

I think I was worried about using pipe 0 because I didn't quite understand the collision potential since that is also used for transmitting. 

I looks like your library handles all of that though.

Caio

**Comment by TMRh20** [comment]
> Was there ever a time when your library's pipes were 1 indexed? Or did I just always have that bug in there?

I'm guessing it was always there, the pipes have always been 0 through 5. It took me a bit to realize there can be up to 7 radios, but it was a simple modification to get it working.

The more I play with this library the more I like it. Nice and straightforward.

**Comment by Hobietime** [comment]
Glad you like it! I wrote it since a lot of first year students were having trouble in a beginner Arduino course.

I'm sorry I haven't approved this yet. I'm currently traveling for work and won't have a lot of Internet access until next week.

Then I will merge this and maybe even try automating updating the docs repo.

**Pull request merged**
